### ISSUE TITLE
Discussão sobre a regra class-methods-use-this

### ISSUE THREAD

**Issue by rickfreitas** [quero-edu/guidelines#57]
No nosso time ja levantamos algumas vezes a discussão sobre manter ou não essa regra, gostaria de trazer para cá para podermos apreciar mais opiniões 😅 
https://eslint.org/docs/rules/class-methods-use-this

Ela ajuda bastante a separar o que deveria ou não estar na classe X, ou até se deveria ser uma classe, mas em alguns casos a classe tem funções que não utilizam o this, mas se remove-las parece que a classe fica um tanto quanto incompleta.

**Comment by toledompm** [comment]
Decidimos manter a regra pois a maioria achou que faz sentido.
