### ISSUE TITLE
Erro ao instalar o pacote utilizando node v16.15.0 (npm v8.10.0)

### ISSUE THREAD

**Issue by rodolfo-santos** [quero-edu/guidelines#79]
Utilizando `node v16.15.0 (npm v8.10.0)`

Ao tentar instalar o pacote com o comando:
`npm install --save-dev @quero/eslint-config-base @quero/eslint-config-typescript`

O seguinte erro é apresentado:
```
npm ERR! Cannot read properties of null (reading 'package')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rodofosantos/.npm/_logs/2022-05-19T12_27_40_722Z-debug-0.log
```

**Comment by vitebo** [comment]
tenta instalar só o `@quero/eslint-config-base` ou o `@quero/eslint-config-typescript` pra descobrir se o erro acontece com os 2 ou só com um deles

**Comment by rodolfo-santos** [comment]
Não tenho permissões nesse repositório, pode conceder ?
