### ISSUE TITLE
Precisa criar templates de issue e PR

### ISSUE THREAD

**Issue by vhoyer** [quero-edu/guidelines#8]

**Comment by vhoyer** [comment]
@danilovaz, tem alguma sugestão de como a gente podia fazer os templates?

**Comment by danilovaz** [comment]
@vhoyer fechando minhas tasks de hj, tento bolar algo com calma aqui e a gente chega em um modelo <3

**Comment by vhoyer** [comment]
deixa eu te dar uma base pra você não ter que pensar tudo sozinho :sweat_smile: (lembrando que esse repo é publico e a gente não ta muito acostumado com isso :D)

**PR:**
```
### Proposta
<!-- o que é a modificação desse PR -->
### Motivação
<!-- qual o problema a ser resolvido por ele -->
```

**Issue:**
```
### Porque isso é um problema?
<!--  -->
```

por favor, sinta-se mais que a vontade para mudar o que quiser na minha sugestão :D

**Comment by iurynogueira** [comment]
O que acham disso para as PRs?

======

* O que esta PR faz / Porque nós precisamos fazer isso?


* Que tipo de mudança foi introduzida?

[ ] Bugfix 🐛 

[ ] Feature ✨ 

[ ] Refactor 🔨 

[ ] Build-Mudança relatada 🔖 

[ ] Outro, por favor descrever:


* Que tipo de teste foi implementado? ✅ 


[ ] Unitário

[ ] Integração/Headless

[ ] Nenhum, porque:


* Observações para o revisor:

**Comment by vhoyer** [comment]
ta, faz muito tempo que essa issue ta abandonada aqui, vamo tentar fechar ela então, aproveitando que cê reviveu ela (vlw pela contribuição), então assim, eu curto deixar separado o "what" e o "why", qq cê acha?

```markdown
* O que esta PR faz?

* Porque nós precisamos fazer isso?

* Que tipo de mudança foi introduzida?

- [ ] Bugfix 🐛 
- [ ] Feature ✨ 
- [ ] Refactor 🔨 
- [ ] Build-Mudança relatada 🔖 
- [ ] Outro, por favor descrever:

* Que tipo de teste foi implementado? ✅ 

- [ ] Unitário
- [ ] Integração/Headless
- [ ] Nenhum, porque:

* Observações para o revisor:
```

E assim eu pessoalmente acho que qqr coisa que é valida colocar no `Observações para o revisor` deveriam estar no próprio repo como documentação/markdown, comentários no código, ou mensagens de commit, e portanto, essa seção fica um pouco redundante, mas também não vejo muito valor em tirar ela, então acho ok a gente continuar com ela no template, qq cê, @iurynogueira, acha dessas mudanças que eu tô propondo?

**Comment by iurynogueira** [comment]
> ta, faz muito tempo que essa issue ta abandonada aqui, vamo tentar fechar ela então, aproveitando que cê reviveu ela (vlw pela contribuição), então assim, eu curto deixar separado o "what" e o "why", qq cê acha?
> 
> ```gfm
> * O que esta PR faz?
> 
> * Porque nós precisamos fazer isso?
> 
> * Que tipo de mudança foi introduzida?
> 
> - [ ] Bugfix 🐛 
> - [ ] Feature ✨ 
> - [ ] Refactor 🔨 
> - [ ] Build-Mudança relatada 🔖 
> - [ ] Outro, por favor descrever:
> 
> * Que tipo de teste foi implementado? ✅ 
> 
> - [ ] Unitário
> - [ ] Integração/Headless
> - [ ] Nenhum, porque:
> 
> * Observações para o revisor:
> ```
> 
> E assim eu pessoalmente acho que qqr coisa que é valida colocar no `Observações para o revisor` deveriam estar no próprio repo como documentação/markdown, comentários no código, ou mensagens de commit, e portanto, essa seção fica um pouco redundante, mas também não vejo muito valor em tirar ela, então acho ok a gente continuar com ela no template, qq cê, @iurynogueira, acha dessas mudanças que eu tô propondo?

Acho que se já tem doc/md para ajudar o revisor ficaria realmente redundante mesmo, podemos remover e colocar uma OBS dizendo que qualquer dúvida consultar a documentação. Podemos abrir PR?

**Comment by vhoyer** [comment]
Acho que sim :D, cê quer fazer isso pra nós?

**Comment by iurynogueira** [comment]
> Acho que sim :D, cê quer fazer isso pra nós?

Quero demais!
